### ISSUE TITLE
[SPONSOR] @murban007

### ISSUE THREAD

**Issue by legendsayantan** [legendsayantan/MsRewards#28]
@murban007

**Provide your app ID below this line.**
-

**Comment by murban007** [comment]
-1063535298-b6288046-fd37-404d-9b8f-b85f85ea9fdf


> Od: "Sayantan Paul" ***@***.***>
> Komu: "legendsayantan/MsRewards" ***@***.***>
> Dátum: 20.11.2024 20:18
> Predmet: [legendsayantan/MsRewards] [SPONSOR] @murban007 (Issue #28)
>

@murban007
Provide your app ID below this line.
Thanks for sponsoring this project! Please keep an eye on this issue, the activation url will be provided soon.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/legendsayantan/MsRewards/issues/28",
"url": "https://github.com/legendsayantan/MsRewards/issues/28",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by legendsayantan** [comment]
Activation link -

https://rewards.is-an.app/?action=redeem&code=29c309646b185550f2568f9b61b9d8be882f1dbaa26f82a248f94b2d3c88baefa4a33ee7983174320ce2e76cfd9ddd353eca683b87168675052e5eb0d91eaa7b52ce0804e00253c2cac99b65ba31efc6be488f84d2a67c696be0a2cde2bcaa08c354ddbe34251c575562ab98e9dd409d3e52189ebe7c2c4bcbc17943d0ee9713e262414f3f219bad504a8b89381e025df12b66dc9595dd4629d20dcfc0a0ce7d9185bf2ef1b9c5b2339a9aa7491d732ac617b0624702c9077588b052c02309cbec60adaa975bf832f9e8901769de45d69f6e60bf5efdff36afedcf3cebe20f7f23059471b0cf199fe459b267a14bce8999588ad29fd82cdafd66370fc2e1b90d&amount=35000
