### ISSUE TITLE
Addition of custom number of searches for turbo search

### ISSUE THREAD

**Issue by Caerus256** [legendsayantan/MsRewards#5]
Hey thank you very much for the turbo search and is working perfectly for my account but it was only searching 3 searches per 15 minutes. could you add a custom number of searches to the settings or increase the limit to 4 searches per 15 minutes since many have limit as 4, since battery is draining very fast.

**Comment by legendsayantan** [comment]
It actually does 4-5 searches every cycle, but counts it as 3. Because not all of the searches are successfully registered by ms and it needs to average that out somehow. I will still investigate into it though.

I haven't noticed much battery drain, but an workaround could be leaving turbo running overnight when the phone is plugged to the charger?

**Comment by Caerus256** [comment]
The counts were always accurate for me. It was never missing the count, so the time and battery are gone to waste. So if it possible please add a manual option.

Thank you
